server:
  port: 4011
spring:
  cloud:
    gateway:
      discovery: 
         locator: 
            enabled: true
            lowerCaseServiceId: true
  application:
    name: hsy-gateway
  main: 
    allow-bean-definition-overriding: true
  redis:
    database: 0
    host: 127.0.0.1
    password: hsy2019
    port: 6379
    lettuce:
      pool:
        max-active: 15
        max-wait: -1
        max-idle: 15
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
