server:
  port: 6011
spring:
  cloud:
    gateway:
      discovery: 
         locator: 
            enabled: true
            lowerCaseServiceId: true
  application:
    name: hsy-gateway
  redis:
    database: 0
    host: 192.168.11.97
    password: hsy2019
    port: 6379
    lettuce:
      pool:
        max-active: 15
        max-wait: -1
        max-idle: 15

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://172.19.248.48:6761/eureka/
